# Generated by Django 3.2.19 on 2023-06-21 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dogImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dog_images/')),
            ],
        ),
        migrations.CreateModel(
            name='analysis_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('dogImg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chkDogImg.dogimg')),
            ],
        ),
    ]
